import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>EZ-POS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to EZ-POS!
        </h1>

        <p className={styles.description}>
          New Here?
          <Link href="/auth/create-account">
            <a>Create an Account</a>
          </Link>
        </p>

        <p className={styles.description}>
          Been Here Before?
          <Link href="/auth/login">
            <a>Login</a>
          </Link>
        </p>
      </main>
    </div>
  )
}

export default Home
